---
name: salt-ssh action
description: GitHub Action for running salt-ssh

inputs:
  #   Action-specific options:
  #     These are action-specific inputs provided for convenience.
  target:
    description: "Specify the targeted minions. Default: '*'."
    required: false
    default: '*'
  function:
    description: "The function to apply to the targeted minions. Default: 'state.highstate'."
    required: false
    default: state.highstate
  arguments:
    description: Additional arguments to pass to the salt-ssh command.
    required: false
  private-key:
    description: The base64-encoded private key to use for connecting to the minions.
    required: false
  known-hosts:
    description: The base64-encoded known_hosts file contents to setup before calling salt-ssh.
    required: false
  known-hosts-file:
    description: The known_hosts file to setup before calling salt-ssh.
    required: false

  #   Options:
  saltfile:
    description: Specify the path to a Saltfile. If not passed, one will be searched for in the current working directory.
    required: false
  config-dir:
    description: "Pass in an alternative configuration directory. Default: '/etc/salt'."
    required: false
  jid:
    description: Pass a JID to be used instead of generating one.
    required: false
  hard-crash:
    description: "Raise any original exception rather than exiting gracefully. Default: False."
    required: false
  no-parse:
    description: Comma-separated list of named CLI arguments (i.e. argname=value) which should not be parsed as Python data types
    required: false
  raw-shell:
    description: Don't execute a salt routine on the targets, execute a raw shell command.
    required: false
  roster:
    description: "Define which roster system to use, this defines if a database backend, scanner, or custom roster system is used. Default: 'flat'."
    required: false
  roster-file:
    description: Define an alternative location for the default roster file location. The default roster file is called roster and is found in the same directory as the master config file.
    required: false
  refresh-cache:
    description: Force a refresh of the master side data cache of the target's data. This is needed if a target's grains have been changed and the auto refresh timeframe has not been reached.
    required: false
  max-procs:
    description: "Set the number of concurrent minions to communicate with. This value defines how many processes are opened up at a time to manage connections, the more running processes the faster communication should be. Default: 25."
    required: false
  extra-filerefs:
    description: Pass in extra files to include in the state tarball.
    required: false
  min-extra-modules:
    description: One or comma-separated list of extra Python modules to be included into Minimal Salt.
    required: false
  thin-extra-modules:
    description: One or comma-separated list of extra Python modules to be included into Thin Salt.
    required: false
  verbose:
    description: Turn on command verbosity, display jid.
    required: false
  static:
    description: Return the data from minions as a group after they all return.
    required: false
  wipe:
    description: Remove the deployment of the salt files when done executing.
    required: false
  rand-thin-dir:
    description: Select a random temp dir to deploy on the remote system. The dir will be cleaned after the execution.
    required: false
  regen-thin:
    description: Trigger a thin tarball regeneration. This is needed if custom grains/modules/states have been added or updated.
    required: false
  python2-bin:
    description: Path to a python2 binary which has salt installed.
    required: false
  python3-bin:
    description: Path to a python3 binary which has salt installed.
    required: false
  pre-flight:
    description: Run the defined ssh_pre_flight script in the roster
    required: false

  #   Target Options:
  #     Target selection options.
  hosts:
    description: List all known hosts to currently visible or other specified rosters
    required: false
  pcre:
    description: Instead of using shell globs to evaluate the target servers, use pcre regular expressions.
    required: false
  list:
    description: Instead of using shell globs to evaluate the target servers, take a comma or whitespace delimited list of servers.
    required: false
  grain:
    description: 'Instead of using shell globs to evaluate the target use a grain value to identify targets, the syntax for the target is the grain key followed by a globexpression: "os:Arch*".'
    required: false
  grain-pcre:
    description: 'Instead of using shell globs to evaluate the target use a grain value to identify targets, the syntax for the target is the grain key followed by a pcre regular expression: "os:Arch.*".'
    required: false
  nodegroup:
    description: Instead of using shell globs to evaluate the target use one of the predefined nodegroups to identify a list of targets.
    required: false
  range:
    description: Instead of using shell globs to evaluate the target use a range expression to identify targets. Range expressions look like %cluster.
    required: false

  #   Additional Target Options:
  #     Additional options for minion targeting.
  delimiter:
    description: "Change the default delimiter for matching in multi-level data structures. Default: ':'."
    required: false

  #   Output Options:
  #     Configure your preferred output format.
  output:
    description: Print the output from the 'salt-ssh' command using the specified outputter.
    required: false
  output-indent:
    description: Print the output indented by the provided value in spaces. Negative values disables indentation. Only applicable in outputters that support indentation.
    required: false
  output-file:
    description: Write the output to the specified file.
    required: false
  output-file-append:
    description: Append the output to the specified file.
    required: false
  no-color:
    description: Disable all colored output.
    required: false
  force-color:
    description: Force colored output.
    required: false
  state-output:
    description: "Override the configured state_output value for minion output. One of 'full', 'terse', 'mixed', 'changes' or 'filter'. Default: 'none'."
    required: false
  state-verbose:
    description: "Override the configured state_verbose value for minion output. Set to True or False. Default: none."
    required: false

  #   SSH Options:
  #     Parameters for the SSH client.
  remote-port-forwards:
    description: Setup remote port forwarding using the same syntax as with the -R parameter of ssh. A comma separated list of port forwarding definitions will be translated into multiple -R parameters.
    required: false
  ssh-option:
    description: Equivalent to the -o ssh command option. Passes options to the SSH client in the format used in the client configuration file. Can be used multiple times.
    required: false

  #   Authentication Options:
  #     Parameters affecting authentication.
  priv:
    description: Ssh private key file.
    required: false
  priv-passwd:
    description: Passphrase for ssh private key file.
    required: false
  ignore-host-keys:
    description: By default ssh host keys are honored and connections will ask for approval. Use this option to disable StrictHostKeyChecking.
    required: false
  no-host-keys:
    description: Removes all host key checking functionality from SSH session.
    required: false
  user:
    description: Set the default user to attempt to use when authenticating.
    required: false
  passwd:
    description: Set the default password to attempt to use when authenticating.
    required: false
  askpass:
    description: Interactively ask for the SSH password with no echo - avoids password in process args and stored in history.
    required: false
  key-deploy:
    description: Set this flag to attempt to deploy the authorized ssh key with all minions. This combined with --passwd can make initial deployment of keys very fast and easy.
    required: false
  identities-only:
    description: Use the only authentication identity files configured in the ssh_config files. See IdentitiesOnly flag in man ssh_config.
    required: false
  sudo:
    description: Run command via sudo.
    required: false
  update-roster:
    description: If hostname is not found in the roster, store the information into the default roster file (flat).
    required: false

  #   Scan Roster Options:
  #     Parameters affecting scan roster.
  scan-ports:
    description: Comma-separated list of ports to scan in the scan roster.
    required: false
  scan-timeout:
    description: Scanning socket timeout for the scan roster.
    required: false

  #   Logging Options:
  #     Logging options which override any settings defined on the
  #     configuration files.
  log-level:
    description: "Console logging log level. One of 'all', 'garbage', 'trace', 'debug', 'profile', 'info', 'warning', 'error', 'critical', 'quiet'. Default: 'warning'."
    required: false
  log-file:
    description: "Log file path. Default: '/var/log/salt/ssh'."
    required: false
  log-file-level:
    description: "Logfile logging log level. One of 'all', 'garbage', 'trace', 'debug', 'profile', 'info', 'warning', 'error', 'critical', 'quiet'. Default: 'warning'."
    required: false

runs:
  using: docker
  image: docker://ghcr.io/amplium/salt-ssh-action:latest
