---
name: Test

on:
  - pull_request
  - push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: |
          sed -i '/image:/s/: .*/: test.dockerfile/' action.yaml

      - uses: ./
        with:
          config-dir: testdata
          roster-file: testdata/roster
          log-level: all
          no-host-keys: true
          ssh-option: StrictHostKeyChecking=no
